services:

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      # Временная папка для клонированных репозиториев
      - /tmp/dep-analyzer:/tmp/dep-analyzer
      - D:\projects\DepAnalyser:/projects/DepAnalyser

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      # Чтобы данные Redis не терялись при перезапуске
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

volumes:
  redis_data: